version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Akash@2001
      MYSQL_DATABASE: CRUD
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-app
    ports:
      - "3000:3000"
    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/CRUD?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/CRUD
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Akash@2001
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - mynetwork
    restart: on-failure

networks:
  mynetwork:

volumes:
  mysql-data:

